### ISSUE TITLE
Awesome `AoCHelper` customization!

### ISSUE THREAD

**Issue by eduherminio** [Morphix84/AdventOfCode#1]
Hey Angus, awesome customization of `AoCHelper` to make it fit your needs!
Would you mind if I link this repository somewhere in AoCHelper's README at some point, as an example of custom usage?

**Comment by Morphix84** [comment]
Sure thing.  AoCHelper is pretty slick.  I had been using my own version of this for several years, but this year I decided to look around at what other people were doing for their AoC Templates and this was one of the most robust IMO for C#.

Main changes I made:

- AoCHelper assumes you're going to build a separate project for each year, I changed it to support year folder structures.
- Took some code from another template to fetch the input automatically.
- Added a github action to add stars to the readme as I unlock them (also taken from another template).

**Comment by eduherminio** [comment]
Thanks!
I think I'll eventually look into supporting multi-year dir structures, but it may be tricky to create something generic enough that people can adapt to their repositories, and not the other way around.
